namespace CombatManager.Database.Models;

public class SpellDto : ISpellDto
{
    public string castingtime { get; set; }
    public string costlycomponents { get; set; }
    public string Name { get; set; }
    public string school { get; set; }
    public string subschool { get; set; }
    public string descriptor { get; set; }
    public string spellLevel { get; set; }
    public string castingTime { get; set; }
    public string components { get; set; }
    public string costlyComponents { get; set; }
    public string range { get; set; }
    public string targets { get; set; }
    public string effect { get; set; }
    public string dismissible { get; set; }
    public string area { get; set; }
    public string duration { get; set; }
    public string shapeable { get; set; }
    public string savingThrow { get; set; }
    public string spellResistence { get; set; }
    public string description { get; set; }
    public string descriptionFormated { get; set; }
    public string source { get; set; }
    public string fullText { get; set; }
    public string verbal { get; set; }
    public string somatic { get; set; }
    public string material { get; set; }
    public string focus { get; set; }
    public string divineFocus { get; set; }
    public string sor { get; set; }
    public string wiz { get; set; }
    public string cleric { get; set; }
    public string druid { get; set; }
    public string ranger { get; set; }
    public string bard { get; set; }
    public string paladin { get; set; }
    public string alchemist { get; set; }
    public string summoner { get; set; }
    public string witch { get; set; }
    public string inquisitor { get; set; }
    public string oracle { get; set; }
    public string antipaladin { get; set; }
    public string assassin { get; set; }
    public string adept { get; set; }
    public string redMantisAssassin { get; set; }
    public string magus { get; set; }
    public string url { get; set; }
    public string slaLevel { get; set; }
    public string preparationTime { get; set; }
    public bool duplicated { get; set; }
    public string acid { get; set; }
    public string air { get; set; }
    public string chaotic { get; set; }
    public string cold { get; set; }
    public string curse { get; set; }
    public string darkness { get; set; }
    public string death { get; set; }
    public string disease { get; set; }
    public string earth { get; set; }
    public string electricity { get; set; }
    public string emotion { get; set; }
    public string evil { get; set; }
    public string fear { get; set; }
    public string fire { get; set; }
    public string force { get; set; }
    public string good { get; set; }
    public string language { get; set; }
    public string lawful { get; set; }
    public string light { get; set; }
    public string mindAffecting { get; set; }
    public string pain { get; set; }
    public string poison { get; set; }
    public string shadow { get; set; }
    public string sonic { get; set; }
    public string water { get; set; }
    public ConditionBonus bonus { get; set; }
    public string potionWeight { get; set; }
    public string divineScrollWeight { get; set; }
    public string arcaneScrollWeight { get; set; }
    public string wandWeight { get; set; }
    public string potionLevel { get; set; }
    public string potionCost { get; set; }
    public string arcaneScrollLevel { get; set; }
    public string arcaneScrollCost { get; set; }
    public string divineScrollLevel { get; set; }
    public string divineScrollCost { get; set; }
    public string wandLevel { get; set; }
    public string wandCost { get; set; }
}